Була присутня на парі.

In [ ]:
import numpy as np

np.__version__

'2.0.2'

Задати вектор

In [ ]:
v = np.array([1, 2, 3, 4, 5], dtype= float)
v

array([1., 2., 3., 4., 5.])

In [ ]:
v[0]

np.float64(1.0)

In [ ]:
v[-1]

np.float64(5.0)

Задати масив

In [ ]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#вивести елемент а23
a[1,2]

np.int64(6)

In [ ]:
#вивести елемент а11
a[0,0]

np.int64(1)

In [ ]:
#вивести елемент а13
a[0,2]

np.int64(3)

In [ ]:
#вивести елемент а22
a[1,1]

np.int64(5)

Вивести тип елементів

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.size

6

In [ ]:
a.shape

(2, 3)

Задати матрицю 3*3

In [ ]:
a = np.array([[11,5,16],[54,100,-6],[14,1001,67]])
a

array([[  11,    5,   16],
       [  54,  100,   -6],
       [  14, 1001,   67]])

Ще один варіант Задати матрицю 3*3

In [ ]:
a = np.matrix([[11,5,16],[54,100,-6],[14,1001,67]])
a

matrix([[  11,    5,   16],
        [  54,  100,   -6],
        [  14, 1001,   67]])

Побудувати діагональ

In [ ]:
diag_a = np.diag(a)
diag_a

array([ 11, 100,  67])

Побудувати діагональну матрицю на основі діагоналі

In [ ]:
a_diag = np.diag(diag_a)
a_diag

array([[ 11,   0,   0],
       [  0, 100,   0],
       [  0,   0,  67]])

Масив, вектор, заповнений нулями

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Створити масив 3*3, заповнити та вивести його значення

In [ ]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

масив 4*4, з числами від 0 до 10

In [ ]:
np.random.randint(11, size=(4,4))

array([[ 0,  3,  2,  3],
       [ 8, 10,  8,  8],
       [ 2,  7,  6,  1],
       [ 9,  1,  3,  9]])

Масив(вектор) заповнений одиницями

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

Масив чисел від 2 до 9 з кроком 3

In [ ]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [ ]:
np.linspace(0,20,5) #початок, кінець, кількість елементів

array([ 0.,  5., 10., 15., 20.])

матриця розміром 3*3

In [ ]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

Транспонувати матрицю

In [ ]:
a = np.array([[66,73,10050], [0,74,13],[380,98,2]])
a

array([[   66,    73, 10050],
       [    0,    74,    13],
       [  380,    98,     2]])

In [ ]:
a.transpose()

array([[   66,     0,   380],
       [   73,    74,    98],
       [10050,    13,     2]])

In [ ]:
a.T

array([[   66,     0,   380],
       [   73,    74,    98],
       [10050,    13,     2]])

Визначник матриці

In [ ]:
a = np.array([[32, 90], [12, 41]])
a

array([[32, 90],
       [12, 41]])

In [ ]:
a_det = np.linalg.det(a)
a_det

np.float64(231.99999999999997)

Множення матриці на число

In [ ]:
a = np.matrix([[33, 12, 90], [200, 300, 111],[9, 1, 0]])
c = a*3
c

matrix([[ 99,  36, 270],
        [600, 900, 333],
        [ 27,   3,   0]])

Додавання матриць

In [ ]:
a = np.matrix([[33, 12, 90], [200, 300, 111],[9, 1, 0]])
b = np.matrix([[3433, 500, 1], [14, 87, 3],[9, 51, 10]])
c = a+b
c

matrix([[3466,  512,   91],
        [ 214,  387,  114],
        [  18,   52,   10]])

Добуток матриць

In [ ]:
a = np.matrix([[33, 12, 90], [200, 300, 111],[9, 1, 0]])
b = np.matrix([[3433, 500, 1], [14, 87, 3],[9, 51, 10]])
c = np.dot(a,b)
c

matrix([[114267,  22134,    969],
        [691799, 131761,   2210],
        [ 30911,   4587,     12]])

Поелементний добуток

In [ ]:
np.multiply(a,b)

matrix([[113289,   6000,     90],
        [  2800,  26100,    333],
        [    81,     51,      0]])

In [ ]:
a/b

matrix([[9.61258375e-03, 2.40000000e-02, 9.00000000e+01],
        [1.42857143e+01, 3.44827586e+00, 3.70000000e+01],
        [1.00000000e+00, 1.96078431e-02, 0.00000000e+00]])

In [ ]:
np.divide(a,b)

matrix([[9.61258375e-03, 2.40000000e-02, 9.00000000e+01],
        [1.42857143e+01, 3.44827586e+00, 3.70000000e+01],
        [1.00000000e+00, 1.96078431e-02, 0.00000000e+00]])

Обернена матриця

In [ ]:
a = np.matrix([[1, -5], [9, 4]])
a_inv = np.linalg.inv(a)
a_inv

matrix([[ 0.08163265,  0.10204082],
        [-0.18367347,  0.02040816]])

Ранг матриці

In [ ]:
rank = np.linalg.matrix_rank(a)
rank

np.int64(2)

In [ ]:
a  = np.array([[0, 4, 6], [-3, -11, -1], [11, 12, 13]])
eigenvalues, eigenvectors = np.linalg.eig(a)

print("\n")
print(eigenvalues)
print("\n")
print(eigenvectors)



[ 15.99614512  -3.82180885 -10.17433627]


[[-0.33445869  0.88122012 -0.11007797]
 [ 0.0719745  -0.31979473  0.90298642]
 [-0.93965795 -0.34811266 -0.41532924]]
